export const NEXT_PUBLIC_BASE_URL = process.env.NEXT_PUBLIC_BASE_URL
export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL
export const NEXT_PUBLIC_COMPANY_BASE_URL = process.env.NEXT_PUBLIC_COMPANY_BASE_URL
